var words = {
    "Anethum graveolens": "dill",
    "Anthemis cotula": "maith",
    "Apium graveolens": "merch",
    "apple cider": "applewine",
    "Arctium plant": "burdock",
    "Artemisia vulgaris": "mugwort",
    "at a distance": "afar",
    "Atropa belladonna": "deadly nightshade",
    "binding commitment": "bend",
    "biological father": "birthfather",
    "biological mother": "birthmother",
    "Brassica oleracea": "wildcole",
    "by chance": "at unset steven",
    "Caesalpinia echinata": "emberwood",
    "Capparis spinosa": "halsewort",
    "capital city": "headbury",
    "carob tree": "codtree",
    "castrated animal": "afired",
    "Ceratonia siliqua": "codtree",
    "Cichorium intybus": "hardhew",
    "commemoration day": "amind day",
    "common law": "folkright",
    "common sense": "motherwit",
    "compound word": "bindword",
    "contrary to": "against",
    "crescent moon": "bentmoon",
    "Cruciferae plant": "charlock",
    "Cynoglossum officinale": "houndstongue",
    "Cytisus scoparius": "broom",
    "domestic violence": "homeheast",
    "Egyptian mongoose": "adderbiter",
    "en passant": "as an aside",
    "Erigeron acris": "bitter fleabane",
    "et cetera": "and so forth",
    "exactly as": "alsuch",
    "explosive material": "blastle",
    "facial bone": "anletbone",
    "family room": "livingroom",
    "Feast Day": "simbleday",
    "Feast of Tabernacles": "Simble of Ingathering",
    "Feast of the Cross": "Holy Rood Day",
    "Feast of the Transfiguration": "Forhallowing Day",
    "Feast of Trumpets": "Simble of Trumpets",
    "Feast of Unleavened Bread": "Simble of Unraised Bread",
    "female animal": "doe",
    "female elf": "elfen",
    "Filipendula ulmaria": "meadowsweet",
    "Foeniculum vulgare": "fennel",
    "for the most part": "altogether",
    "future tense": "toward tide",
    "Galium aparine": "cleavers",
    "Geranium plant": "cranesbill",
    "Helleborus niger": "lungwort",
    "Helminthotheca echioides": "bristly oxtongue",
    "hot chocolate": "bitterbrew",
    "house of commons": "Folkthing",
    "Humulus lupulus": "himmel",
    "immune to": "unfazed by",
    "imperative mood": "biddingly mood",
    "indicative mood": "beckoningly mood",
    "indirect object": "selfstanding ware",
    "inferior nasal concha": "lower nosely spinner",
    "inkhorn terms/words": "sharewords",
    "intersex person": "baddle",
    "in a moment": "at a braid",
    "in action": "afoot",
    "in advance": "beforehand",
    "in any manner": "anywise",
    "in different directions": "abroad",
    "in front of": "afore",
    "in general": "altogether",
    "in opposition to": "against",
    "in passing": "as an aside",
    "in process": "afoot",
    "in spite of": "notwithstanding",
    "in the air": "alift",
    "in the area": "afoot",
    "in total": "all told",
    "in two parts": "atwain",
    "jamais vu": "neverseen",
    "Jack o'Lantern": "willothewisp",
    "je ne sais quoi": "Godknowswhat",
    "just as": "alsuch",
    "kapok tree": "silk-treewool tree",
    "labia majora": "greater ladylips",
    "labia minora": "lesser ladylips",
    "labor union": "workship",
    "lager beer": "light beer",
    "Lake Albert": "Albert Mere",
    "Lake Athabasca": "Athabasca Mere",
    "Lake Baikal": "Baikal Mere",
    "Lake Balkhash": "Balkash Mere",
    "Lake Michigan": "Michigan Mere",
    "language arts": "Thodsprack Lists",
    "lapis lazuli": "skystone",
    "legal disposition": "besight",
    "legal provision": "besight",
    "Leontopodium alpinum": "athelwhite",
    "life course": "lifeswend",
    "lingua franca": "shared tongue",
    "linguistic purism": "sheerspeechcraft",
    "liquid filth": "addle",
    "logographic rune": "begriprown",
    "lunar phase": "moon shape",
    "lunate bone": "moonbone",
    "machine gun": "shacklegun",
    "magnesium oxide": "bitter earth",
    "maitre d'hotel": "upkeep",
    "make sense": "make wits",
    "makes sense": "makes wits",
    "malicious person": "atterling",
    "Marchantia polymorpha": "liverwort",
    "Mardi Gras": "Shrove Tuesday",
    "marine park": "waterfrith",
    "martial arts": "wyecrafts",
    "mea culpa": "my bad",
    "medicinal plant": "leechwort",
    "mediterranean sea": "Wendle Sea",
    "mega annum": "Greatyear",
    "mental affliction": "bedevil",
    "Mentha pulegium": "dwarfdwostle",
    "misappropriative guest": "stealguest",
    "monkeypuzzle tree": "tailapepuzzle tree",
    "multilanguage word": "wanderword",
    "nasal bone": "nosely bone",
    "natural logarithm": "infold",
    "natural selection": "drain of life",
    "nizhny novgorod": "Nether Newton",
    "nolens volens": "willy-nilly",
    "notary public": "logbookande",
    "noxious weed": "Hell weed",
    "nuclear bomb": "kernelblastle",
    "nuclear reactor": "kerneloven",
    "nuclear weapon": "kernelweapon",
    "nutritional therapist": "greenmonger",
    "nutritional value": "wholesome worth",
    "obsessive compulsive disorder": "brainlock",
    "occipital bone": "skullend",
    "old fashioned": "stickinthemud",
    "Old Testament": "Old Bond",
    "out of order": "amiss",
    "out of place": "awry",
    "Parietaria officinalis": "lichwort",
    "Paris quadrifolia": "oneberry",
    "past participle": "forthwitten dealnimmer",
    "past tense": "forthwitten tide",
    "Persicaria bistorta": "adderwort",
    "Peucedanum officinale": "hogsfennel",
    "Picris echioides": "bristly oxtongue",
    "place of residence": "abode",
    "poisonous animal": "atterdeer",
    "Polypodium vulgare": "everfern",
    "poor creature": "arming",
    "prayer time": "benetide",
    "precious stone": "arkenstone",
    "present tense": "anward tide",
    "Prunus spinosa": "blackthorn",
    "raw petroleum": "black gold",
    "Rosmarinus officinalis": "bothen",
    "Rumex plant": "dock",
    "Qara Qoyunlu": "Black Sheep Turkmen",
    "Sambucus nigra": "black elder",
    "Senecio vulgaris": "mean groundsel",
    "sexual intercourse": "amone",
    "Silene dioica": "hareseye",
    "Sinapis alba": "kedlock",
    "social intercourse": "amone",
    "socially barbaric": "backward",
    "Solanum americanum": "Americkish black nightshade",
    "Solanum nigrum": "black nightshade",
    "Solanum ptychanthum": "eastern black nightshade",
    "Stachys officinalis": "bishopswort",
    "subjunctive mood": "undertheedingly mood",
    "supreme court judge": "alderdeemer",
    "Symphytum officinale": "blackwort",
    "tarsal bone": "anklebone",
    "tax rebate": "anshot",
    "tax return": "anshot",
    "the Baltic states": "Baltland",
    "thoracic vertebra": "backridgebone",
    "Thymus serpyllum": "fill",
    "tried and true": "acost",
    "Ulex Europaeus": "furze",
    "Utricularia plant": "bladdewort",
    "Vaccinium oxycoccos": "fenberry",
    "venomous animal": "atterdeer",
    "Verbascum thapsus": "haresbeard",
    "Vitex agnus-castus": "hemptree",
    "warrant officer": "biddle",
    "wicked sorcery": "attercraft",
    "with difficulty": "arvethly",
}
