var words = {
    "a la carte": "by the list",
    "ad infinitum": "endlessly",
    "All Saints' Day": "All Hallows' Day",
    "Anethum graveolens": "dill",
    "Anno Domini": "in the year of our Lord",
    "Anthemis cotula": "maith",
    "apart from": "aside from",
    "Apium graveolens": "merch",
    "apple cider": "applewine",
    "Arctium plant": "burdock",
    "Artemisia vulgaris": "mugwort",
    "Ascension Day": "Upgangday",
    "astronomical rings": "Gemma's rings",
    "at a distance": "afar",
    "Atropa belladonna": "deadly nightshade",
    "aurora australis": "southern lights",
    "aurora borealis": "northern lights",
    "binding commitment": "bend",
    "biological father": "birthfather",
    "biological mother": "birthmother",
    "blood vessel": "edder",
    "Brassica oleracea": "wildcole",
    "by chance": "at unset steven",
    "Caesalpinia echinata": "emberwood",
    "Capparis spinosa": "halsewort",
    "capital city": "headborough",
    "carob tree": "codtree",
    "castrated animal": "afired",
    "Ceratonia siliqua": "codtree",
    "Chinese character": "Hanrown",
    "Cichorium intybus": "hardhew",
    "circulatory system": "bloodstream",
    "civet cat": "slipcat",
    "coat of arms": "kinshield",
    "coat of mail": "burn",
    "commemoration day": "amind day",
    "common law": "folkright",
    "common sense": "motherwit",
    "compound word": "bindword",
    "concentration camp": "shandstead",
    "contrary to": "against",
    "Corpus Christi": "Wistforwandering Day",
    "counterfeit goods": "apeware",
    "coup d'etat": "putch",
    "covered area": "deck",
    "cover with": "lay on",
    "crescent moon": "bentmoon",
    "Cruciferae plant": "charlock",
    "cuneiform bone": "wedgebone",
    "Cynoglossum officinale": "houndstongue",
    "Cytisus scoparius": "broom",
    "deoxyribonucleic acid": "unasourseedsweetkernly sour",
    "domestic violence": "homeheast",
    "drainage basin": "watershed",
    "Egyptian mongoose": "adderbiter",
    "en passant": "as an aside",
    "environmentally friendly": "green",
    "Erigeron acris": "bitter fleabane",
    "escape pod": "fleepod",
    "et cetera": "and so forth",
    "ethmoid bone": "sievebone",
    "exactly as": "alsuch",
    "expiration date": "sellby",
    "explosive material": "blastle",
    "extramarital affair": "wedbreach",
    "facial bone": "anletbone",
    "fait accompli": "done deal",
    "falsely accuse": "forwray",
    "family room": "livingroom",
    "Feast Day": "simbleday",
    "Feast of Tabernacles": "Simble of Ingathering",
    "Feast of the Cross": "Holy Rood Day",
    "Feast of the Transfiguration": "Forhallowing Day",
    "Feast of Trumpets": "Simble of Trumpets",
    "Feast of Unleavened Bread": "Simble of Unraised Bread",
    "female animal": "doe",
    "female elf": "elfen",
    "female wolf": "wolven",
    "femme fatale": "maneater",
    "fifth columnist": "backfriend",
    "Filipendula ulmaria": "meadowsweet",
    "flotsam and jetsam": "seabits and strew",
    "flying buttress": "loftbow",
    "Foeniculum vulgare": "fennel",
    "foreign country": "farland",
    "foreign land": "elland",
    "foreign nation": "eltheed",
    "for the most part": "altogether",
    "frontal bone": "foreskull",
    "future tense": "toward tide",
    "Galium aparine": "cleavers",
    "Geranium plant": "cranesbill",
    "graphics tablet": "drawing pad",
    "guinea pig": "seapig",
    "hamate bone": "hookbone",
    "haptic suit VR": "aped handling",
    "harpy eagle": "kingshawk",
    "Helleborus niger": "lungwort",
    "Helminthotheca echioides": "bristly oxtongue",
    "herbal book": "wortbook",
    "hot chocolate": "bitterbrew",
    "house of commons": "Folkthing",
    "Humulus lupulus": "himmel",
    "hyoid bone": "tonguebone",
    "ice skates": "sleighshoes",
    "ignis fatuus": "will o' the wisp",
    "immune to": "unfazed by",
    "imperative mood": "biddingly mood",
    "indicative mood": "beckoningly mood",
    "indirect object": "selfstanding ware",
    "inferior nasal concha": "lower nosely spinner",
    "inkhorn terms/words": "sharewords",
    "inner diameter": "inner bore",
    "intersex person": "baddle",
    "in a moment": "at a braid",
    "in action": "afoot",
    "in advance": "beforehand",
    "in any manner": "anywise",
    "in different directions": "abroad",
    "in front of": "afore",
    "in general": "altogether",
    "in opposition to": "against",
    "in passing": "as an aside",
    "in process": "afoot",
    "in spite of": "notwithstanding",
    "in the air": "alift",
    "in the area": "afoot",
    "in total": "all told",
    "in two parts": "atwain",
    "Ivory Coast": "Elpsbone Shore",
    "jamais vu": "neverseen",
    "Jack o'Lantern": "willothewisp",
    "je ne sais quoi": "Godknowswhat",
    "just about": "almost",
    "just as": "alsuch",
    "kapok tree": "silk-treewool tree",
    "labia majora": "greater ladylips",
    "labia minora": "lesser ladylips",
    "labor union": "workship",
    "lacrimal bone": "tearbone",
    "lager beer": "light beer",
    "Lake Albert": "Albert Mere",
    "Lake Athabasca": "Athabasca Mere",
    "Lake Baikal": "Baikal Mere",
    "Lake Balkhash": "Balkash Mere",
    "Lake Michigan": "Michigan Mere",
    "language arts": "Thodsprack Lists",
    "lapis lazuli": "skystone",
    "legal disposition": "besight",
    "legal provision": "besight",
    "Leontopodium alpinum": "athelwhite",
    "life course": "lifeswend",
    "lingua franca": "shared tongue",
    "lingual bone": "tonguebone",
    "linguistic purism": "sheerspeechcraft",
    "liquid filth": "addle",
    "logographic rune": "begriprown",
    "lunar phase": "moon shape",
    "lunate bone": "moonbone",
    "luteinizing hormone": "beyellowenning spur",
    "machine gun": "shacklegun",
    "magnesium oxide": "bitter earth",
    "maître d'": "headberman",
    "maitre d'hotel": "upkeep",
    "make sense": "make wits",
    "makes sense": "makes wits",
    "malicious person": "atterling",
    "manta ray": "seadevil",
    "Marchantia polymorpha": "liverwort",
    "Mardi Gras": "Shrove Tuesday",
    "marine park": "waterfrith",
    "martial arts": "wyecrafts",
    "maternal granddaughter": "daughterdaughter",
    "maternal grandson": "daughterson",
    "mea culpa": "my bad",
    "medicinal plant": "leechwort",
    "mediterranean sea": "Wendle Sea",
    "mega annum": "Greatyear",
    "mental affliction": "bedevil",
    "Mentha pulegium": "dwarfdwostle",
    "Mesozoic Era": "Creepdeer Eld",
    "misappropriative guest": "stealguest",
    "mobile phone": "handset",
    "monkeypuzzle tree": "tailapepuzzle tree",
    "Mother Nature": "Mother Earth",
    "multilanguage word": "wanderword",
    "nasal bone": "nosely bone",
    "natural logarithm": "infold",
    "natural selection": "drain of life",
    "nitric acid": "strongwater",
    "nizhny novgorod": "Nether Newton",
    "nolens volens": "willy-nilly",
    "non obstante": "notwithstanding",
    "notary public": "logbookande",
    "noxious weed": "Hell weed",
    "nuclear bomb": "kernelblastle",
    "nuclear reactor": "kerneloven",
    "nuclear weapon": "kernelweapon",
    "nutritional therapist": "greenmonger",
    "nutritional value": "wholesome worth",
    "obsessive compulsive disorder": "brainlock",
    "occipital bone": "skullend",
    "old fashioned": "stickinthemud",
    "Old Testament": "Old Bond",
    "out of order": "amiss",
    "out of place": "awry",
    "Parietaria officinalis": "lichwort",
    "Paris quadrifolia": "oneberry",
    "past participle": "forthwitten dealnimmer",
    "past tense": "forthwitten tide",
    "paternal granddaughter": "sonsdaughter",
    "paternal grandson": "sonson",
    "Persicaria bistorta": "adderwort",
    "Peucedanum officinale": "hogsfennel",
    "Picris echioides": "bristly oxtongue",
    "place of residence": "abode",
    "poisonous animal": "atterdeer",
    "polar bear": "icebear",
    "Polypodium vulgare": "everfern",
    "poor creature": "arming",
    "Portuguese man-of-war": "seabladder",
    "post mortem": "afterdeath",
    "prayer time": "benetide",
    "precious stone": "arkenstone",
    "present tense": "anward tide",
    "Prunus spinosa": "blackthorn",
    "raw petroleum": "black gold",
    "Rosmarinus officinalis": "bothen",
    "Rumex plant": "dock",
    "Qara Qoyunlu": "Black Sheep Turkmen",
    "Sambucus nigra": "black elder",
    "sea creature": "seadeer",
    "sea nymph": "seaelfen",
    "sea passage": "seafareld",
    "Senecio vulgaris": "mean groundsel",
    "sexual intercourse": "amone",
    "Silene dioica": "hareseye",
    "Sinapis alba": "kedlock",
    "social intercourse": "amone",
    "socially barbaric": "backward",
    "Solanum americanum": "Americkish black nightshade",
    "Solanum nigrum": "black nightshade",
    "Solanum ptychanthum": "eastern black nightshade",
    "solid matter": "fastshaft",
    "Stachys officinalis": "bishopswort",
    "stalked crinoid": "sea lily",
    "subjunctive mood": "undertheedingly mood",
    "submarine sandwich": "grinder",
    "supreme court judge": "alderdeemer",
    "Symphytum officinale": "blackwort",
    "tarsal bone": "anklebone",
    "tax rebate": "anshot",
    "tax return": "anshot",
    "the Baltic states": "Baltland",
    "thoracic vertebra": "backridgebone",
    "Thymus serpyllum": "fill",
    "tried and true": "acost",
    "Ulex Europaeus": "furze",
    "unstalked crinoid": "feather star",
    "Utricularia plant": "bladdewort",
    "Vaccinium oxycoccos": "fenberry",
    "venomous animal": "atterdeer",
    "Verbascum thapsus": "haresbeard",
    "Vitex agnus-castus": "hemptree",
    "warrant officer": "biddle",
    "wicked sorcery": "attercraft",
    "with difficulty": "arvethly",
}
