words = {
    "capital city": "headburg",
    "Feast day religious": "simbleday",
    "Feast of Tabernacles": "Simble of Ingathering",
    "Feast of the Cross": "Holy Rood Day",
    "Feast of the Transfiguration": "Forhallowing Day",
    "Feast of Trumpets": "Simble of Trumpets",
    "Feast of Unleavened Bread": "Simble of Unraised Bread",
    "inkhorn terms/words": "sharewords",
    "indirect object": "selfstanding ware",
    "inferior nasal concha": "lower nosely spinner",
    "in spite of": "notwithstanding",
    "immune to": "unfazed by",
    "hot chocolate": "bitterbrew",
    "house of commons": "Folkthing",
    "house of lords": "Athelthing",
    "hope of a ressurection": "aristhyght",
    "jamais vu": "neverseen",
    "Jack o'Lantern": "willothewisp",
    "je ne sais quoi": "Godknowswhat",
    "kapok tree": "silk-treewool tree",
    "labia majora": "greater ladylips",
    "labia minora": "lesser ladylips",
    "labor union": "workship",
    "lager beer": "light beer",
    "language arts": "Thodsprack Lists",
    "lapis lazuli": "skystone",
    "life course": "lifeswend",
    "life of the mind": "intellectual",
    "lingua franca": "shared tongue",
    "linguistic purism": "sheerspeechcraft",
    "lunar phase": "moon shape",
    "lunate bone": "moonbone",
    "machine gun": "shacklegun",
    "magnesium oxide": "bitter earth",
    "maitre d'hotel": "upkeep",
    "make sense": "hold",
    "makes sense": "holds",
    "Mardi Gras": "Shrove Tuesday",
    "marine park": "waterfrith",
    "martial arts": "wyecrafts",
    "mea culpa": "my bad",
    "mediterranean sea": "Great Sea",
    "mega annum": "Greatyear",
    "mental affliction": "bedevil",
    "meter poetry": "tal rhythm",
    "misappropriative guest": "stealguest",
    "monkeypuzzle tree": "tailapepuzzle tree",
    "multilanguage word": "wanderword",
    "nasal bone": "nosely bone",
    "natural logarithm": "infold",
    "natural selection": "drain of life",
    "nizhny novgorod": "Nether Newton",
    "nolens volens": "willy-nilly",
    "notary public": "logbookande",
    "noxious weed": "Hell weed",
    "nuclear bomb": "kernelblaster",
    "nuclear reactor": "kerneloven",
    "nuclear weapon": "kernelweapon",
    "nutritional therapist": "greenmonger",
    "nutritional value": "wholesome worth",
    "obsessive compulsive disorder": "brainlock",
    "occipital bone": "skullend",
      "old fashioned": "stickinthemud",
  "Old Testament": "Old Bond",
}
