/* 

The words in the wordbook must start with a lowercase letter, and cannot contain spaces
since the translator uses the space character to make up the words, meaning that a space
would be recognised as a marker for the end of a word and start of a new one, rather than a part of the word
like in the case of a cappella, which is why the word is written as acappella in the wordbook.

*/


var wordbook = {
    "acappella": "mouthglee",
    "acappellas": "mouthglees",
    "a-la-carte": "by-the-list",
    "aardvark": "antbear",
    "aardvarks": "antbears",
    "abacus": "reckonboard",
    "abacuses": "reckonboards",
    "abandon": "forsake",
    "posteriorly": "abaft",
    "abandonment": "forsaking",
    "abandoning": "forsaking",
    "abandoned": "forsook",
    "abase": "shame",
    "abased": "shamed",
    "abasing": "shaming",
    "abash": "ashame",
    "abashed": "ashamed",
    "abashinh": "ashaming",
    "abate": "ease",
    "abated": "eased",
    "abating": "easing",
    "abattoir": "slaughterhouse",
    "abattoirs": "slaughterhouses",
    "abbess": "mother",
    "abbesses": "mothers",
    "abbreviation": "offshortening",
    "abbreviating": "offshortening",
    "abbreviations": "offshortenings",
    "abbreviate": "offshorten",
    "abdicate": "step down",
    "abdicated": "stepped down",
    "abdication": "stepping down",
    "abdicating": "stepping down",
    "abdomen": "quith",
    "abdomens": "quithes",
    "abduct": "kidnap",
    "abduction": "kidnapping",
    "abducted": "kidnapped",
    "aberrant": "black-sheep",
    "aberration": "way-outness",
    "abet": "goad",
    "abetted": "goaded",
    "abetting": "goading",
    "abettination": "goading",
    "abhor": "loathe",
    "abhorred": "loathed",
    "abhorring": "loathing",
    "ability": "skill",
    "abilities": "skills",
    "abject": "low",
    "abjure": "forswear",
    "abjured": "forsworn",
    "abjuring": "forswearing",
    "ablactate": "wean",
    "ablactating": "weaning",
    "ablactated": "weaned",
    "ablation": "offtaking",
    "ablations": "offtakings",
    "ablative": "atbraidingly",
    "ablaut": "offlloud",
    "able": "fit",
    "ablute": "wash",
    "ablution": "washing",
    "abluted": "washed",
    "abnegate": "forgo",
    "abnegated": "forwent",
    "abnegation": "forgoing",
    "abnormal": "amiss",
    "abnormality": "amissily",
    "abolish": "end",
    "abolished": "ended",
    "abolition": "ending",
    "abominable": "loathsome",
    "aboriginal": "inborn",
    "aboriginals": "firstfolks",
    "aborigine": "firstfolk",
    "abort": "lay off",
    "aborting": "laying off",
    "aborted": "laid off",
    "abortion": "forbirthing",
    "abound": "overflow",
    "abounded": "overflowed",
    "abounding": "overflowing",
    "abrasion": "graze",
    "abridge": "forshorten",
    "abridged": "foreshortened",
    "abridging": "foreshortening",
    "abrupt": "anon",
    "abruptly": "anonly",
    "abscond": "break out",
    "absconded": "broke out",
    "absconding": "breaking out",
    "absence": "offwardness",
    "absent": "offward",
    "absenteeism": "offwardness",
    "absinthe": "wormwood drink",
    "absolute": "outright",
    "absolution": "outrightly",
    "absolutely": "wholly",
    "absolve": "forgive",
    "absolved": "forgave",
    "absolving": "forgiving",
    "absolvation": "forgiving",
    "absorb": "up-soak",
    "absorbed": "up-soaked",
    "absorbing": "up-soaking",
    "absorbtion": "up-soaking",
    "abstain": "withhold",
    "abstaining": "withholding",
    "abstained": "withheld",
    "abstinence": "forhaveness",
    "abstract": "dreamlike",
    "abstraction": "dreamlikeness",
    "abundance": "fullsomeness",
    "abundant": "overflowing",
    "abuse": "scathe",
    "abused": "scathed",
    "abusing": "scathing",
    "abysmal": "lowest",
    "abyss": "netherworld",
    "acacia": "thorntree",
    "academia": "loredom",
    "academic": "lorewise",
    "academically": "lorewisely",
    "açaí": "koleberry",
    "acai": "koleberry",
    "accede": "thware",
    "acceded": "thwared",
    "acceding": "thwareing",
    "accelerate": "swiften",
    "accelerating": "swifting",
    "acceleration": "swifteness",
    "accent": "tonguefall",
    "accept": "ontake",
    "accepted": "ontook",
    "acceptable": "thewsome",
    "access": "gateway",
    "accessed": "gatewayed",
    "accessible": "at hand",
    "accessory": "deedmate",
    "accident": "befall",
    "accidental": "unwitting",
    "accompany": "follow",
    "accompanied": "followed",
    "accomplish": "fulfill",
    "accomplishing": "fulfilling",
    "accord": "deal",
    "accordion": "bellowharp",
    "according to": "as of",
    "account": "ledger",
    "accountant": "teller",
    "accumulate": "heap",
    "accumulation": "unheaping",
    "accurate": "spot-on",
    "accusation": "bewraying",
    "accusative": "wrayingly",
    "accuse": "wray",
    "accustom": "wean",
    "accustomed": "wont",
    "acephalous": "headless",
    "acetone": "sourghost",
    "achievement": "bringing-forth",
    "acid": "sour",
    "acne": "redmeal",
    "aconite": "wolfsbane",
    "acoustics": "dinlore",
    "acquaint": "befriend",
    "acquaintance": "friend",
    "acquiesce": "bow",
    "acquire": "earn",
    "acquisition": "windfall",
    "acrobat": "stringtumb",
    "acropolis": "high town",
    "across": "over",
    "act": "do",
    "action": "deed",
    "activate": "switch on",
    "activated": "switched on",
    "active": "switched on",
    "activist": "browbeater",
    "activists": "browbeaters",
    "actor": "showplayer",
    "actress": "showplayer",
    "actual": "sooth",
    "actually": "indeed",
    "acupuncture": "pinpricking",
    "acute": "sharp",
    "AD": "in the year of our lord",
    "ad": "in the year of our lord",
    "ad infinitum": "forevermore",
    "adamant": "unyielding",
    "adaptable": "onwending",
    "adapted": "onwended",
    "adapter": "fayfitter",
    "add": "fay",
    "added": "fayed",
    "addict": "soughtier",
    "addicted": "soughty",
    "addiction": "craving",
    "addition": "faying",
    "additional": "bycoming",
    "additionally": "furthermore",
    "address": "link",
    "addressed": "bespoke",
    "addressing": "bespeaking",
    "adept": "skillful",
    "adequate": "right",
    "adhere": "cling",
    "adherent": "follower",
    "adherents": "followers",
    "adiposis": "overweight",
    "adjacent": "near",
    "adjective": "mark-word",
    "adjunct": "helpmate",
    "adjust": "withset",
    "admonish": "chide",
    "administer": "wield",
    "administered": "wielded",
    "administering": "wielding",
    "administration": "shiredom",
    "admiral": "fleetleader",
    "admirals": "fleetleaders",
    "admire": "looked up to",
    "admiration": "bewondering",
    "admirations": "bewonderings",
    "admission": "intaking",
    "admit": "intake",
    "adolescence": "youthhood",
    "adolescent": "youth",
    "adopt": "take in",
    "adoption": "fostering",
    "adorable": "comely",
    "adorn": "bedight",
    "adrenaline": "thringweald",
    "adulation": "hallowing",
    "adult": "grownup",
    "adulthood": "waxenhood",
    "adultery": "wedbreach",
    "adumbrate": "outline",
    "adumbrating": "outlining",
    "adumbrated": "outlined",
    "adumbration": "outlining",
    "advance": "inroads",
    "advanced": "manifold",
    "advancing": "striding",
    "advantage": "boon",
    "advantageous": "helpful",
    "advection": "tobearing",
    "advent": "coming",
    "adventure": "happening",
    "adventurous": "daring",
    "adverb": "byword",
    "adversarial": "thwartsome",
    "adversary": "foe",
    "adversity": "ill",
    "adversive": "withersome",
    "advertize": "boost",
    "advertisement": "boostering",
    "advice": "tip",
    "advisable": "redesome",
    "advise": "Beread",
    "advised": "Bereaded",
    "advocacy": "boost",
    "advocate": "plead for",
    "aerial": "skywards",
    "aerodynamic": "streamlined",
    "aerodynamics": "loftcraft",
    "aeronaut": "flyer",
    "aerospace": "skycraft",
    "sir": "ghosts",
    "aesthetic": "comely",
    "affair": "fling",
    "affect": "lead to",
    "affection": "fondness",
    "affectionate": "loving",
    "affiance": "betroth",
    "affinity": "leaning",
    "affirm": "foraye",
    "affirmative": "aye",
    "affix": "stick on",
    "afflict": "ail",
    "affluence": "wealth",
    "affluent": "wealthy",
    "afraid": "aghast",
    "Africa": "highsun",
    "age": "tide",
    "ages": "tides",
    "aged": "elderly",
    "agenda": "to-do-list",
    "agendas": "to-do-lists",
    "agent": "follower",
    "agents": "followers",
    "agglomerate": "huddle",
    "agglomerated": "huddled",
    "agglomerating": "huddling",
    "agglomeration": "crowding",
    "agglutinate": "wordlink",
    "agglutinated": "wordlinked",
    "agglutinating": "wordlinking",
    "agglutination": "wordlinking",
    "aggression": "go-getting",
    "aggressing": "go-getting",
    "aggressive": "fightsome",
    "aggressor": "raider",
    "aggressors": "raiders",
    "agile": "nimble",
    "agitated": "stir",
    "agitation": "worry",
    "aglet": "needling",
    "agoraphobia": "steadfear",
    "agree": "settle on",
    "agreed": "settled on",
    "agreeable": "likeworthy",
    "agreement": "deal",
    "agricultural": "fieldish",
    "agricultur": "field",
    "agrarian": "fieldish",
    "agriculture": "farming",
    "agrostology": "grasslore",
    "aichmophobia": "needlefright",
    "aid": "help",
    "aids": "helps",
    "aiding": "helping",
    "aided": "helped",
    "aimsome": "singleminded",
    "AIDS": "Earned Bodyweir Scantness Sickness (EBSS)",
    "aim": "goal",
    "aim at": "sight",
    "air": "wind",
    "airforce": "skymight",
    "airplane": "wingcraft",
    "airport": "flightfield",
    "airship": "Zeppelin",
    "aisle": "path",
    "alarm": "waker",
    "alas": "alack",
    "albedo": "whiteness",
    "albino": "whiteling",
    "album": "whitebook",
    "albumen": "egg white",
    "alchemy": "orecraft",
    "alcohol": "booze",
    "alcoholic": "sot",
    "alert": "awake",
    "algorithm": "reckonwrit",
    "alien": "wayout",
    "alienate": "befremd",
    "alienation": "unfriendliness",
    "align": "set up",
    "allegiance": "truthness",
    "allegory": "likeness",
    "allergy": "overfeeling",
    "allergies": "overfeelings",
    "alleviate": "allay",
    "alley": "walk",
    "alliance": "bond",
    "allied": "banded",
    "alligator": "broadmouthnix",
    "alligators": "broadmouthnixes",
    "alliteration": "staffrime",
    "allocate": "earmark",
    "allotment": "alloting",
    "allow": "let",
    "allowable": "thwaresome",
    "alloy": "mix",
    "All Saints Day": "allhallowsmas",
    "allude": "hint at",
    "allure": "draw to",
    "ally": "Ithoft",
    "almanac": "yearbook",
    "alphabet": "futhorc",
    "altar": "weved",
    "alter": "shift",
    "altercation": "flite",
    "alternate": "waver",
    "alternative": "other",
    "altitude": "height",
    "altruism": "selflessness",
    "altruistic": "selfless",
    "aluminum": "canstuff",
    "Alzheimers": "the long goodbye",
    "Alzheimer": "the long goodbye",
    "amass": "gather",
    "amateur": "greenhorn",
    "amazon": "bandfighters",
    "ambassador": "landspellsman",
    "amber": "brimstone",
    "ambidextrous": "both-handed",
    "ambience": "mood",
    "ambiguous": "twiwordy",
    "ambiguity": "twiwordiness",
    "ambivalence": "waver",
    "ambivert": "twigoer",
    "ambiverted": "twigoing",
    "ambulance": "sickwain",
    "ambulant": "roving",
    "ambush": "net",
    "ameliorate": "better",
    "amen": "soothly",
    "America": "New World",
    "amicable": "friendly",
    "amigo": "friend",
    "ammonia": "hartshorn",
    "amnesia": "blackout",
    "amoeba": "shapeshifter",
    "amorphous": "shapeless",
    "amount": "come up",
    "ampersand": "andtoken",
    "amphibian": "lurrow",
    "amphibious": "two-breathed",
    "amphitheater": "playstow",
    "ample": "broad",
    "amplifier": "forstronger",
    "amplify": "outbroaden",
    "amplified": "outbroadened",
    "amplitude": "breadth",
    "amputate": "cut off",
    "amputated": "cut off",
    "amputation": "cutting off",
    "amusement": "fun",
    "amusing": "listing",
    "anachronism": "mistiming",
    "anaconda": "whipsnake",
    "anesthetic": "unsightly",
    "anagram": "stavewrixel",
    "anal": "bottom",
    "analgesic": "numbing",
    "analog": "gear-driven",
    "analogy": "alikeword",
    "analyze": "look at",
    "anarchism": "lawlesshood",
    "anarchy": "lawlessness",
    "anastomosis": "shunt",
    "anathema": "forputting",
    "anatomy": "bodylore",
    "ancestor": "forebearer",
    "ancestors": "forebearers",
    "ancestry": "strain",
    "ancient": "hoary",
    "ancient times": "yoretide",
    "andiron": "firedog",
    "androgyny": "werewifehood",
    "android": "manhue",
    "anemometer": "windmeter",
    "anemone": "windrose",
    "anesthesia": "unfeeler",
    "angel": "rotherer",
    "angle": "nook",
    "anguish": "woe",
    "angular": "hyrned",
    "animal": "being",
    "animate": "besoul",
    "animation": "drawn film",
    "anime": "dawnlandish",
    "animosity": "hatered",
    "annals": "yearbookings",
    "annelid": "ringworm",
    "annex": "onend",
    "annihilate": "wipe out",
    "annihilation": "wrecking",
    "anniversary": "yearday",
    "Anno Domini": "in the year of our lord",
    "annotate": "mark",
    "annotation": "marking",
    "announce": "ban",
    "announcement": "oncouthing",
    "annoy": "irk Barnes",
    "annoying": "irksome Barnes",
    "annual": "yearbook",
    "annul": "fordo",
    "annuli astronomici": "Gemmas Rings",
    "anoint": "smear",
    "anonymous": "nameless",
    "anorexia nervosa": "foodshy",
    "antagonist": "fiend",
    "antarctic": "southend",
    "Antarctica": "South End",
    "antecedence": "beforemath",
    "antediluvian": "foreflood",
    "antenna": "yardhorn",
    "antelope": "pronghorn",
    "anterior": "fore",
    "anthem": "folksong",
    "anthocyanin": "flowerblue",
    "anthology": "reader",
    "Anthropocene": "Mantide",
    "anthropology": "theedlore",
    "antivaxx": "witherimp",
    "antibiotic": "gainrodlifeanwork",
    "antisemite": "Jewhater",
    "anticipate": "foretell",
    "anticlockwise": "widdershins",
    "antics": "odd behaveness",
    "anticonstitutionally": "witherlawwritly",
    "antidisestablishmentarianism": "gainunstathelingmanness",
    "antidote": "atterloathe",
    "antigen": "offweirstuff",
    "antihero": "banestar",
    "antilope": "buck",
    "antimatter": "gainstuff",
    "antipathy": "mislike",
    "antipope ": "gainfather",
    "antiquated": "careworn",
    "antique": "barn-find",
    "antiquity": "olden days",
    "antiseptic": "withersmite",
    "antistatism": "witherlawwardness",
    "antistatist": "leedward witherling",
    "antitoxin": "gainatter",
    "antler": "blowhorn",
    "antonym": "witherword",
    "anulus": "ring",
    "anus": "endring",
    "anxiety": "worry",
    "aorta": "loftleat",
    "apart": "cleaved",
    "apart from": "aside",
    "apartment": "flat",
    "apathetic": "samewise",
    "aperture": "opening",
    "apex": " tip",
    "aphid": "greenfly",
    "aphrodisiac": "lustdrive",
    "apiculture": "beekeeping",
    "apogee": "hightip",
    "apologise": "say sorry",
    "apology": " sorry",
    "apostate": "backslider",
    "apostasy": "backsliding",
    "apostle": " errandbearer",
    "apothecary": "libshop",
    "apparel": "clothes",
    "apparent": "seeming",
    "apparently": "seemingly",
    "appeal": "call upon",
    "appealing": "fair",
    "appear": "show up",
    "appearance": "blee",
    "appease": "soothe",
    "appellation": "name",
    "appendage": "limb",
    "appendicitis": "blindgut addle",
    "appendix": "organ blindgut",
    "appetite": "craving",
    "appetizer": "starter",
    "application": "bearing",
    "applause": "standing and clapping",
    "apply": "beseech",
    "appoint": "afix",
    "appreciate": "be thankful",
    "apprehension": "foreboding",
    "apprentice": " beginner",
    "approach": " means",
    "approaching": "nearing",
    "appropriate": "befitting",
    "approve": "let",
    "approximate": "rough",
    "approximately": "about",
    "appurtenance": "sidemarking",
    "April": "Eastermonth",
    "apron": "barmcloth",
    "apt": "fit",
    "aquaculture": "fishfarming",
    "aqualung": " waterlung",
    "aquamarine": "seagreen",
    "aquaphobia": " waterfear",
    "aquaphobic": "afraid of the water",
    "aquaplaning": "watergliding",
    "aquarium": "fishglass",
    "aquatic": "waterly",
    "aqueduct": "waterleat",
    "aqueous": "watery",
    "arable": "ploughsome",
    "arachnid": "eightlegger",
    "arboreal": "treewise",
    "arbitrary": " whimsy",
    "arboretum": "treestead",
    "arc": "bow",
    "arcade": "playhall",
    "arch": "bow",
    "archaic ": "timeworn",
    "archangel": "highangel",
    "archeology": "olddomlore",
    "archeopterix": "stonelayed",
    "archer": "bowman",
    "archery": "bowmanship",
    "archfoe": "devil",
    "archipelago": "itune",
    "architect": "highcrafter",
    "architecture": "shell",
    "architrave": "silebeam",
    "archive": "backup",
    "arctic": "bear Ursa Minor",
    "Arctic": "Land of the Midnight Sun",
    "ardor": "keenness",
    "arduous": "backbreaking",
    "area": "land",
    "argent": "silver",
    "Argentina": "Silverland",
    "argon": "idlestuff",
    "arguable": "moot",
    "argue": "flite",
    "argument": " flite",
    "arguseyed": "allseeing",
    "aridity": "drought",
    "Aries": "The Fleecy Star",
    "aristocratic": "fullblooded",
    "arithmetic": "tellcraft",
    "arm": "handweapon",
    "armadillo": "shellbear",
    "arming": "weaponing",
    "armistice": "truce",
    "armor": "begear",
    "armory": "shieldhouse",
    "army": "dright",
    "aroma": "smell",
    "around": "about",
    "arouse": "stir",
    "arquebus": "matchlock",
    "arrange": "fix",
    "arrangement": "layout",
    "array": "lay out",
    "arrest": "nab",
    "arrive at": "reach",
    "arrogant": "proud",
    "arsenal": "weaponhoard",
    "arsonist": "fireraiser",
    "art": "craft",
    "artery": "loftblood adder",
    "artesian": "thringrising",
    "arthritis": "lithbollow",
    "artichoke": "eatthistle",
    "article": "thing",
    "artificer": "maker",
    "artificial": "manmade",
    "artillery": "gunware",
    "artisan": "handyman",
    "arts artistry": "craft",
    "Asatruar maur": "Esetrother",
    "asbestos": "thrumstone",
    "ascend": "climb",
    "Ascension Day": "Gangday",
    "ascent": "upgoing",
    "asexual": "swiveless",
    "Asia": "the East",
    "Asian race": "Far-Eastern",
    "asparagus": "sparrowgrass",
    "asphalt": " streettar",
    "aspin": "philipdog",
    "assail": "beset",
    "assassin": "hitman",
    "assault": "onset",
    "assemble": "cleave",
    "assembly": "forgathering",
    "assent": "samethick",
    "asset": "holding",
    "assiduous": "hopping",
    "assign": "allot",
    "assimilate": "inblend",
    "assist": "help",
    "assistance": "help",
    "assistant": "helper",
    "associate": "formeng",
    "association": "hookup",
    "assume": "deem",
    "assure": "forsaek",
    "assured": "forsaeked",
    "assuring": "forsaeking",
    "aster": "starbloom",
    "asterisk": "star",
    "asteroid": "roomrock",
    "asthma": "angbreast",
    "astonish": "astound",
    "astonished": "astounded",
    "astonishing": "amazing",
    "astral": "rotherly",
    "astrarium": "tungletimer",
    "astrolabe": "starreckoner",
    "astrology": "starcraft",
    "astronaut": "starman",
    "astronomy": "starlore",
    "astute": "shrewd",
    "asymmetrical": "lopsided",
    "asylum": "grith",
    "asymptote": "ameetend",
    "atavism": "throwback",
    "atelier": "workshop",
    "atheism": "godlessness",
    "athest": "godless",
    "ative": " ingly",
    "atlas": "land book",
    "atmosphere": "welkin",
    "atom": "grot",
    "atrocious": "frightful",
    "atrophy": "withering",
    "attack": "raid",
    "attack helicopter": "strikenchopper",
    "attain": "reach",
    "attempt": "seek",
    "attend": "hearken",
    "attendant": "steward",
    "attention": "heed",
    "attest": "witness",
    "attic": "loft",
    "attire": "cladding",
    "attitude": "standing",
    "attorney": "lawman",
    "attract": "draw",
    "attractive": "comely",
    "attraction": "wondersight",
    "attribute": "ownship",
    "auction": "biddingsale",
    "audacious": "daring",
    "audacity": "gall",
    "audible": "hearly",
    "audience": "listeners",
    "audio": "loud",
    "augment": "eke",
    "August": "Weedmonth",
    "augury": "freit",
    "aunt": "father's sister",
    "aurora": "dawning",
    "aurora australis": "southern lights",
    "aurora borealis": "northern lights",
    "aurum": "gold",
    "auscultation": "harkening",
    "austere": "yarewit",
    "austerity": "hardliness",
    "Autism": "selfdom",
    "Australia": "New Holland",
    "Austria": "Austrick",
    "autarchy": "thralldom",
    "author": "writer",
    "authentic": "true",
    "authority": "headship",
    "auto": "self",
    "autodidact": "selftaught",
    "automaker": "wainwright",
    "automatic": "selfworking",
    "automobile": " selfshifter",
    "autonomy": "selflaw",
    "autonym": "selfname",
    "autopsy": "open bodyunderseeching",
    "Autotune": "Selftune",
    "autumn": "fall",
    "auxiliary": "backup",
    "avail": "dow",
    "available": "free",
    "avalanche": "snowslide",
    "avant garde": "cutting edge",
    "avarice": "greed",
    "avatar": "fleshbilth",
    "avenge": "wreak",
    "avenue": "drive",
    "average": "mean",
    "avert": "forestall",
    "aviary": "birdhouse",
    "aviation": "flight",
    "aviator": "birdman",
    "avid": "raring",
    "avocado": "butter pear",
    "avoid": "miss",
    "avow": "swear",
    "award": "bestow",
    "axis": "axle",
    "azimuth": "south hern",
    "Aztec": "Heronlandish",
    "azure": "haw",
    "bacchanal": "Wassail",
    "bacil": "rodling",
    "bachelor": "stag",
    "bacon": "British fatty ham",
    "bacteria": "rodlife",
    "badger": "brock",
    "badminton": "featherball ",
    "baggage": "belongings",
    "baguette": " French loaf",
    "bail out": "pack out",
    "bailiff": "sheriff",
    "balaclava": "head-sock",
    "balance": "steady",
    "bald": "bare",
    "baleen": "whalebone",
    "ballad": "jingle",
    "ballet": "fairtumb",
    "ballistics": "guncraft",
    "ballistic": "shootlore",
    "balloon": "bladder",
    "baloney": "twaddle",
    "baluster": "holdershaft",
    "bamboo": "treereed",
    "banal": "everyday",
    "banality": "everydayness",
    "banalize": "hackney",
    "banana": "moonpod",
    "bandage": "bind",
    "bandit": "crook",
    "banish": "cast out",
    "banister": "handsill",
    "bank": "benchhouse",
    "banknote": "greenback",
    "bankrupt": "broke",
    "banner": "jack",
    "banquet": "feed",
    "baobab": "apebreadwood",
    "baptism": "christening",
    "baptize": "christen",
    "bar": "ban",
    "barb": "prick",
    "barber": "Haircutter",
    "barbarian": "heathen",
    "barbarous": "heartless",
    "barbeque": "stickwork",
    "barbecue": "stickwork",
    "bargain": "cheapen",
    "barge": "scow",
    "barnacle": "curlfooter",
    "barometer": "weatherglass",
    "baroness": "freelady",
    "baron": "freelord",
    "barracks": "wyehut",
    "barracuda": "toothfish",
    "barrage": "wall",
    "barrel": "coop",
    "barrelmaker": "cooper",
    "barren": "bare",
    "barricade": "bar",
    "barrier": "forsetting",
    "barter": "wrixletrade",
    "base": "build",
    "baseball": "hardball",
    "baseless": "groundless",
    "basement": "underground",
    "basic": "barebones",
    "basically": "mostly",
    "basil": "mistle",
    "basis": "bedrock",
    "basket": "maund",
    "basketball": "hoopball",
    "bass": "wicker fishbaskethaske",
    "basin": "bowl",
    "bastard": "whoreson",
    "batik": "batik",
    "batrachian": "tailless",
    "battalion": "throng",
    "batter": "beat",
    "battery": "cell pack",
    "battery bear": "moon bear",
    "battle": "hurlyburly",
    "battlefield": "clashfield",
    "battleship": "fightship",
    "Bavarian": "Bairish",
    "bay": "inlay",
    "bayonet": "goad",
    "BCE": "Before Nowen Eld (BNE)",
    "bce": "Before Nowen Eld (BNE)",
    "beak": "bill",
    "beat": "smite",
    "beau": "swain",
    "beautiful": "sheenful",
    "beauty": "sheen",
    "because": "as",
    "bedaub": "besmear",
    "beef": "cowflesh",
    "behaviour": "bearing",
    "behavior": "bearing",
    "beige": "dusty",
    "Belarus": "Whiterus",
    "belfry": "bergfrith",
    "Belgium": "Belgland",
    "belladonna": "dwale",
    "bellicose": "brawly",
    "belligerent": "hotheaded",
    "benefactor": "well-doer",
    "benefit": "help",
    "benevolent": "kindhearted",
    "benign": "harmless",
    "berate": "upbraid",
    "beret": "flathat",
    "berg": "barrow",
    "beryllium": "greenstuff",
    "besiege": "beleaguer",
    "bestiality": "deerlust",
    "betray": "backstab",
    "betrayer": "deep throat",
    "beverage": "drink",
    "bi": "two",
    "biannual": "halfyearly",
    "bias": "leaning",
    "Bible": "Holy Book",
    "bibulous": "spongy",
    "bicameral": "tworoomed",
    "Bicol": "Sidefolk",
    "bicycle": "twowheeler",
    "bidet": "saddlebath",
    "bidirectional": "twoway",
    "biennially": "halfyearly",
    "biennial": "halfyearly",
    "biker": "wheeler",
    "bikini": "two-bit",
    "bilateral": "twosided",
    "bile bear": "moon bear",
    "bill": "reckoning",
    "billabong": "oxbow",
    "billion": "thrisand",
    "binary": "twile",
    "binoculars": "field glasses",
    "biochemistry": "lifeblendlore",
    "biochemical": "lifeblendish",
    "biography": "lifetale",
    "biology": "lifelore",
    "biome": "lifehood",
    "BIOS": "BIOS (Bottom Input Output Setup)",
    "bipedal": "twolegged",
    "birthplace": "birthstead",
    "biscuit": "cookie",
    "bisect": "cleave",
    "bisexual": "twiluster",
    "bison": "wisent",
    "bittern": "havelbleat",
    "bitumen": "blacktop",
    "bivalve": "clam",
    "bizarre": "weird",
    "blackpowder": "blackdust",
    "Blairite": "Blairer",
    "blame": "wite",
    "blasphemy": "swearing",
    "blatant": "glaring",
    "blemish": "mar",
    "blemishless": "clean",
    "blizzard": "snowstorm",
    "block": "cleat",
    "blond": "fair",
    "blouse": "keel",
    "bludgeon": "club",
    "blue": "blow",
    "blurb": "outline",
    "bodyguard": "holdand",
    "boffin": "witshipper",
    "bog": "mire",
    "bogus": "wrong",
    "boil": "well up",
    "boilersuit": "overalls",
    "bomb": "blaster",
    "bombard": "beshoot",
    "bombardment": "beshooting",
    "bonanza": "windfall",
    "bondage": "yolk",
    "bonnet": "hood",
    "bon": "good",
    "boomerang": "andglider",
    "boondocks": "nowhere",
    "bordello": "whorehouse",
    "border": "brim",
    "boron": "weldstuff",
    "boss": "foreman",
    "botany": "wortlore",
    "bottle": "flask",
    "bouillon": "brew",
    "boulevard": "broadway",
    "boulevardier": "townfrealser",
    "boundary": "end",
    "bountiful": "bighearted",
    "bouquet": "bloomset",
    "bourbon": "Kentucky lifewater",
    "bourgeois": "hidebound",
    "boustrophedon": "oxwend",
    "boutique": "wearshop",
    "bovine": "cowlike",
    "bowel": "gut",
    "bra": "breastshirt",
    "brace": "fastener",
    "bracelet": "wristband",
    "braces": "toothfasteners",
    "bracket": "holdknot",
    "braggart": "boaster",
    "braille": "Blind's rune",
    "brake": "undershot",
    "branch": "bough",
    "brassiere": "armward",
    "brave": "bold",
    "bravo": "well done",
    "brawl": "flite",
    "bray": "heehaw",
    "Brazil": "Emberland",
    "Brazilian": "Emberlandish",
    "Brazilwood": "rudwood",
    "breakable": "brittle",
    "breve": "short",
    "brewery": "brewhouse",
    "bribe": "buy off",
    "bricbrac": "by hook or by crook",
    "brick": "bakestone",
    "bricolage": "happenmade",
    "brief": "say",
    "briefs": "legless undershorts",
    "brilliance": "brightness",
    "brilliant": "shining",
    "brisk": "swift",
    "broccoli": "sproutcole",
    "brochure": "flyer",
    "bromine": "stenchstuff",
    "bronze": "copperbrass",
    "browser": "web crawler",
    "bruise": "lill",
    "brunch": "morgenmete",
    "brunette": "brown",
    "brush": "brust",
    "brutal": "tough",
    "bryophyte": "moss",
    "buccaneer": "freebooter",
    "bucket": "pail",
    "buckle": "fasten",
    "Buddhism": "Buddhadom",
    "budget": "nest egg",
    "buffalo": "wild ox",
    "buffer": "ward",
    "buffet": "foodboard",
    "buffoon": "clown",
    "bullet": "slug",
    "bulletin": "newtidings",
    "bullion": "ingots",
    "bulldozer": "mickle shovel",
    "bully": "manhandle",
    "bun": "puff",
    "bunch": "lot",
    "bungalow": "flackdwelling",
    "bungler": "addlebrain",
    "buoy": "beacon",
    "bureau": "board",
    "bureaucracy": "beadledom",
    "burgeon": "bud",
    "burglar": "stealer",
    "burglary": "housebreaking",
    "burgle": "steal",
    "burlesque": "funnish",
    "bus": "folkwain",
    "bust": "chest",
    "butcher": "fleshmonger",
    "butler": "steward",
    "butter": "Milksmear",
    "button": "switcher",
    "buzzard": "mousehawk",
    "bypass": "skirt",
    "bypast": "bygone",
    "byte": "eightcleft",
    "cabal": "backroom-dealings",
    "cabaret": "club",
    "cabarets": "clubs",
    "cabbage": "kole",
    "cabinet": "hutch",
    "cable": "wire",
    "cables": "wires",
    "caboose": "ward wagon",
    "cabooses": "ward wagons",
    "cacao": "brownbean",
    "cache": "hoard",
    "caches": "hoards",
    "cacophony": "rattle",
    "cactus": "fatthistle",
    "cactuses": "fatthistles",
    "cadaver": "shell",
    "cadaverous": "deathly",
    "cadet": "forefighter",
    "cadets": "forefighters",
    "cadmium": "wodan",
    "cafe": "leafwosroom",
    "cafeteria": "food hall",
    "cage": "bower",
    "cajole": "softsoap",
    "calamari": "cuttlefish",
    "calamaries": "cuttlefish",
    "calcanes": "heelbone",
    "calcium": "milkstuff",
    "carbonate": "lime",
    "calculate": "reckon",
    "calculated": "reckoned",
    "calculation": "tale",
    "calculator": "handreckoner",
    "calculus": "reckoning",
    "calendar": "daybook",
    "calendars": "daybooks",
    "calisthenics": "drills",
    "calligraphy": "longhand",
    "calligrapher": "longhandsmith",
    "callous": "hardened",
    "calm": "lull",
    "calms": "lulls",
    "calmed": "lulled",
    "calming": "lulling",
    "caluminate": "grime",
    "caluminates": "grimes",
    "caluminating": "griming",
    "caluminated": "grimed",
    "calque": "loanshift",
    "caluminator": "backbiter",
    "calyx": "bloomleaf",
    "camel": "olvend",
    "camels": "olvend",
    "camera": "sightshooter",
    "cameras": "sightshooters",
    "camouflage": "dapple",
    "camouflages": "dapples",
    "camomile": "maylix",
    "camp": "leger",
    "camped": "legged",
    "camps": "legers",
    "camping": "bedding",
    "campaign": "take the stump",
    "campaigned": "took the stump",
    "campaigning": "taking the stump",
    "campus": "yard",
    "campuses": "yards",
    "canal": "leat",
    "cancel": "stop",
    "cancer": "deathlump",
    "cancerous": "deathlumping",
    "candelabrum": "glimtree",
    "candidate": "runner",
    "candidates": "runners",
    "candied": "sweetened",
    "candy": "sweets",
    "canine": "hound",
    "cannon": "dunspar",
    "canon": "dunspar",
    "canons": "dunspars",
    "cannonball": "dunsparball",
    "cannonballs": "dunsparballs",
    "cannibal": "maneater",
    "cannibals": "maneater",
    "cannibalism": "maneating",
    "canoe": "dugout",
    "cantaloupe": "rockmug",
    "cantaloupes": "rockmugs",
    "canvas": "hemp",
    "canvases": "hemps",
    "canyon": "gulch",
    "canyons": "gulches",
    "capable": "fitworthy",
    "capacitor": "bearer",
    "capacitors": "bearers",
    "capacity": "room",
    "cape": "mantle",
    "capital": "wealth",
    "capital city": "headburg",
    "capitalism": "wealthwield",
    "capitalist": "silk stocking",
    "capitalization": "blockwrit",
    "capitalisation": "blockwrit",
    "capricious": "fickle",
    "capsize": "keel",
    "capsise": "keel",
    "captain": "headman",
    "caption": "underwrit",
    "captivate": "wile",
    "captive": "penned",
    "captivity": "trap",
    "capture": "nail",
    "car": "wain",
    "caravan": "tradewagon",
    "carbon": "chark",
    "caramel": "Tagger",
    "carburetor": "forelofter",
    "carburetors": "forelofters",
    "carcass": "bones",
    "card": "sheet",
    "cardboard": "headboard",
    "cardiac": "heart",
    "cardinal": "redbird",
    "career": "calling",
    "caress": "fondle",
    "cargo": "draft",
    "cargos": "drafts",
    "caribou": "reindeer",
    "carnal": "fleshly",
    "carnation": "nailling",
    "carnivore": "meateater",
    "carnivores": "meateaters",
    "carouse": "birl",
    "carousel": "merry-wend",
    "carpal": "wrist",
    "carpenter": " woodworker",
    "carpentry": "woodcraft",
    "carpet": "stepcloth",
    "carriage": "bearing",
    "carrot": "more",
    "carry": "bear",
    "cartilage": "grissel",
    "cartouche": "deckwrit",
    "cartridge": "bag",
    "case": "hull",
    "cashew": "kidneyapple",
    "cashewnut": "kidneynut",
    "casing": "shell",
    "casino": "bethall",
    "cast": "anbewarp",
    "castle": "burg",
    "castrate": "geld",
    "casual": "breezy",
    "catalog": "list",
    "catapult": "stonehauler",
    "catch": "snare",
    "catechism": "frodleering",
    "catechize": "grill",
    "categorize": "fade",
    "caterpillar": "cawlworm",
    "cathedral": "headchurch",
    "catheter": "leat",
    "cathode": "downway",
    "catholic": "broadchurch",
    "catkin": "bloomtail",
    "cattle": "cows",
    "Caucasian": "white",
    "caucasian": "white",
    "cauldron": "kettle",
    "cauliflower": "bloomcole",
    "cause": "beget",
    "caustic": "burning",
    "cautery": "tharm tool",
    "caution": "wariness",
    "cautious": "chary",
    "cavalier": "horseman",
    "cavaliers": "horsemen",
    "cavalry": "horsemen",
    "cave": "hidle",
    "caves": "hidles",
    "cavewomen": "cleavewomen",
    "cavewoman": "cleavewoman",
    "cavemen": "cleavemen",
    "caveman": "cleaveman",
    "caviar": "stoorroe",
    "cavil": "carp",
    "cavity": "dint",
    "cease": "stop",
    "ceasefire": "truce",
    "cecum": "blinde gut",
    "cecograph": "blindwriter",
    "cede": "yield",
    "cedilla": "zedling",
    "ceiling": "firstroof",
    "celebrate": "frealse",
    "celebration": "frealsing",
    "celery": "fenroot",
    "celestial": "heavenly",
    "celestial bow": "rainbow",
    "celestial sphere": "rother",
    "cell": "hole",
    "cellar": "clove",
    "cellulose": "treestand",
    "Celtic": "Celtish",
    "cemetery": "graveyard",
    "censorship": "cleaning",
    "censure": "chide",
    "census": "folkscoring",
    "cent": "penny",
    "centaur": "horsemennish",
    "centimeter": "hundredthmete",
    "centipede": "thousandfoot",
    "center": "kernel",
    "central": "middle",
    "centurion": "hundfrea",
    "century": "yearhundred",
    "cereal": "morningcorn",
    "certain": "wis",
    "certainly": "wisly",
    "certainty": "wishood",
    "certificate": "beshining",
    "certify ": "witness",
    "cerulean": "swail blue",
    "cerumen": "earwax",
    "Cesar": " overlord",
    "cesium": "silverwhite",
    "chain": "shackle",
    "chair": "seat",
    "chaiselongue": "longseat",
    "chalice": "bowl",
    "chalk": "limestone",
    "challenge": "knot",
    "chamber": "room",
    "chameleon": "fayingask",
    "chance": "luck",
    "chancellor": "gatekeeper",
    "change": "shift",
    "channel": "fairway",
    "chaos": "mess",
    "Charlemagne": "Charles the Great",
    "character": "clay",
    "chard": "Fowleaf",
    "charge": "fill",
    "charged": "owing",
    "charitable": "kind",
    "charity": "help",
    "charity organization": "bedehouse",
    "charlatan": "swindler",
    "charm": "spell",
    "charming": "friendly",
    "charter": "rightsledging",
    "chase": "hotfoot",
    "chasten": "wreak",
    "chastise": "wreak",
    "chastize": "wreak",
    "castigate": "wreak",
    "chauffeur": "driver",
    "cheat": "shark",
    "check": "avisun",
    "checkers": "drafts",
    "cheer": "gladden",
    "cheese": "milkcurd",
    "chemistry": "blendlore",
    "cherish": "hold dear",
    "cherry": "chirsh",
    "chestplate": "chesthelm",
    "chez": "at",
    "chic": "fancy",
    "chief": "ringleader",
    "chieftain": "heretough",
    "chikungunya": "upbend driff",
    "chili": "hotcride",
    "chimpanzee": "mockman",
    "China": "Midric",
    "Characters": "runes",
    "chivalrous": "big",
    "chivalry": "knightliness",
    "chlorine": "bleachstuff",
    "chlorophyll": "leafgreen",
    "chocolate": "muckeats",
    "choice": "choosing",
    "cholesterol": "gallvat",
    "chrestomathy": "nuttlecouthness",
    "Christian": "Christen",
    "Christianity": "Christendom",
    "Christmas": "Yule",
    "chromosome": "lifepith",
    "chromatid": "lifepithhalf",
    "chromium": "shinestuff",
    "chronic": "",
    "chronicle": "ledger",
    "chronology": "timeline",
    "chrysanthemum": "goldbloom",
    "church": "holihouse",
    "cider": "apple wine",
    "cigar": "smoke",
    "cigars": "smokes",
    "cigarette": "smoke",
    "cigarettes": "smokes",
    "cinema": "bilths",
    "cinemas": "bilths",
    "cinquefoil": "fiffinger",
    "cipher": "dern",
    "circa": "about",
    "circle": "ring",
    "circuit": "ringway",
    "circulate": "flow",
    "circulation": "flow",
    "circulatory system": "bloodstream",
    "circumcise": "cut",
    "circumference": "rim",
    "circumflex": "stavehat",
    "circumnavigate": "umship",
    "circumspect": "careful",
    "circumstance": "doom",
    "circumstances": "umstands",
    "circumvent": "shortcut",
    "circus": "big top",
    "cirrocumulus": "curlcloud",
    "citizen": "townsman",
    "citizenship": "boroughership",
    "citroen": "sourapple",
    "city": "stead",
    "civet cat": "slipcat",
    "civil": "folk",
    "civil law": "folklaw",
    "civilian": "meanfolk",
    "civility": "hoveliness",
    "clade": "bough branch",
    "cladogram": "boughbilth",
    "clairvoyance": "throughsight",
    "claim": "call",
    "clamor": "din",
    "clan": "body",
    "clarify": " shed light on",
    "clarinet": "silversucker",
    "classic": "token",
    "classical": "tokenly",
    "classification": "tagging",
    "classify": "tag",
    "claustrophobia": "narrowfear",
    "clavicle": "keybone",
    "clear": "sharp",
    "clearing": "glade",
    "clearly": "sheerly",
    "clergy": " church",
    "clergyman": "churchman",
    "cliche": "hackneyed",
    "cliché": "hackneyed",
    "climate": "loftlay",
    "cloaca": "cloke",
    "clock": " timer",
    "clockwise": "sunwise",
    "clone": "twin",
    "close": "near",
    "co": "fellow",
    "coagulate": "clot",
    "coalition": "block",
    "coast": "seaboard",
    "coastline": "shoreline",
    "coat of arms": "kinshield",
    "cocaine": "snowdust",
    "coccyx": "tailbone",
    "cochlea": "hearsnail",
    "cockroach": "shave",
    "cocoa": "mucknut",
    "coconut": "skulnut",
    "code": "riddlewrit",
    "coeval": "evenold",
    "coffee": "brew",
    "coffer": "hoardvat",
    "coffin": "through",
    "cognate": "kinword",
    "cognizant": "aware",
    "cohabit": "live together",
    "coherence": "weenness",
    "coin": "mint",
    "coincide": "inbefall",
    "coincidence": "happenso",
    "coitus": "swiving",
    "cojones": "balls",
    "colic": "bellyharm",
    "collapse": "downfall",
    "colleague": "workmate",
    "collect": "gather",
    "collection": "gathering",
    "colonize": "settle",
    "colony": "settling",
    "color": "hue",
    "column": "upright",
    "combat": "fight",
    "combination": "binding",
    "combine": "bind",
    "combustible":  "fireworthy ",
    "comedian": "laughtersmith",
    "comedy": "funplay",
    "comet": "shooting star",
    "comfort": "strengthen",
    "comfortable": " soft",
    "comestible": "eating",
    "comic": "funny",
    "command": "bid",
    " commander": " head",
    "commandment": "behest",
    "commemorate": "mind",
    "commemoration": "minding",
    "commence": "begin",
    "commensurate": "fitting",
    "comment": "bemark",
    "commentary": "input",
    "commenting": "bemarking",
    "commerce": "business",
    "commercial": "businesswise",
    "commissioner": "intrustee",
    "commit": "plight",
    "committed": "plighted",
    "committing": "plighting",
    "common": "shared",
    "CE": "In the year of Our Lord",
    "commonly": "meanly",
    "commonwealth": "meanwealth",
    "commotion": "unrest",
    "communicate": "share",
    "communicative": "chatty",
    "communion": "fellowship",
    "communism": "thralldom",
    "communist": "red",
    "community": "shire",
    "compact": "deal",
    "companion": "fellow",
    "company": "business",
    "comparative": "overlikening",
    "compare": "liken",
    "comparable": " alike",
    "compass": "eighttoken",
    "compassion": "feeling",
    "compassionate": "kind",
    "compatible": "kindred",
    "compatriot": "kinsman",
    "compel": "fordrive",
    "compelling": "fordriving",
    "compelled": "fordrove",
    "compensation": "frover",
    "competent": "fit",
    "compete": "match up",
    "competition": "bidding",
    "compile": "put together",
    "compiler": "togetherputter",
    "compiled": "put together",
    "compiling": "togetherputting",
    "complain": "whine",
    "complete": "fulfill",
    "completely": "outright",
    "complex": "manifold",
    "complexion": "hue",
    "compliant": "toward",
    "complicate": "maze",
    "complicated": "knotty",
    "compliment": "Flatter",
    "complimentary": "sweasely",
    "compline": "nightsong",
    "component": "underdealt",
    "compose": "make",
    "composer": "swinsmith",
    "composition": "layoutIsetness",
    "compound": "cocktail",
    "comprehensive": "allin",
    "comprise": "make up",
    "compromise": "tradeoff",
    "compunction": "qualm",
    "computation": "reckoning",
    "computer": "reckoner",
    "computers": "reckoners",
    "comrade": "fellow",
    "concatenat": "therbinding",
    "conceal": "hide",
    "concealment": "hiding",
    "conceivable": "thoughtworthy",
    "conceive": "beget",
    "concentrate": "meet",
    "concentrated": "crammed",
    "concentration camp": "shandstead",
    "concentric": "ringed",
    "concern": "care",
    "concerning": "as for",
    "concert": "ileethering",
    "concept": "minds eye",
    "conception": "minds eye",
    "conclude": "end",
    "conclusion": "ending",
    "concrete": "beton",
    "concurrently": "meanwhile",
    "concussion": "shell shock",
    "condemn": "doom",
    "condemned the": "doomed",
    "condemner the": "deemster",
    "condescend": "belittle",
    "condition": "onlay",
    "condom": "warding",
    "condominium": "housetown",
    "conduct": "lead",
    "cone": "taper",
    "confectionary": "sweets",
    "confederacy": "rikesband",
    "confederate": "friend",
    "confederation": "bond",
    "confer": "bestow",
    "conference": "meeting",
    "confess": "acknowledge",
    "confession": "acknowledging",
    "confidence": "belief",
    "configuration": "setting",
    "confine": "lock in",
    "confirm": "strengthen",
    "confirmation": "strengthening",
    "confiscate": "filch",
    "conflagration": "fire",
    "conflict": " fight",
    "confluence": "eameet",
    "conform": " dovetail",
    "conformism": "evenlyinghood",
    "conformity": "evenlying",
    "confound": "befuddle",
    "confront": "take on",
    "confuse": "befuddel",
    "confusing": "manifold",
    "confusion": "muddling",
    "confute": "overstale",
    "congregate": "forgather",
    "congress": "gathering",
    "conics": "kegglelore",
    "conjugate": "bend",
    "conjunction": "linking word",
    "connect": "link",
    "conquer": "do down",
    "conquest": "overwin",
    "consanguinity": "kinship",
    "conscience": "thewing",
    "conscious": "aware",
    "consciousness": "awareness",
    "conscript": "draft",
    "consecrate": "bless",
    "consecutively": " straight",
    "consent": "leave",
    "conservation": "orholding",
    "conserve": "orhold",
    "consequence": "aftermath",
    "consequently": "hence",
    "consider": "heed",
    "consideration": "thought",
    "consist": "made",
    "consists": "is made",
    "consisted": "made",
    "consisting": "made",
    "consistency": "weenness",
    "consistent": "weenly",
    "console": "frover",
    "consolation": "froverness",
    "consonant": "withlide",
    "conspicuous": "Sightly",
    "conspiracy": "plot",
    "conspire": "plot",
    "constant": "ongoing",
    "constitution": "clay",
    "constraint": "thwing",
    "constrict": "tighten",
    "constricted": "tightened",
    "consulation": "bereding",
    "consult": "seewith",
    "consulted": "sawwith",
    "consume": "eat up",
    "consumed": "eaten up",
    "consuming": "eating up",
    "consumerism": "intakerhood",
    "consumer": "intaker",
    "consummate": "crack",
    "consumption": "intaking",
    "contact": "get",
    "contain": "hold",
    "container": "holder",
    "contaminate": "befoul",
    "contemplate": "yondthink",
    "contemplation": "thought",
    "contemporary": "todays",
    "contempt": "loathing",
    "contemptuous": "shanding",
    "contend": "set",
    "contended": "set",
    "content": "happy",
    "contention": "wrangling",
    "contest": "match",
    "context": "light",
    "contiguous": "abutting",
    "continent": "mainland",
    "continuation": "Astandendness",
    "continue": "go on",
    "continuing": "going on",
    "continues": "goes on",
    "continued": "went on",
    "continuous": "unbroken",
    "contort": "writhe",
    "contract": "bond",
    "contradict": "gainsay",
    "contradiction": "gainsaying",
    "contrary": "against",
    "contrast": "sunder",
    "controversy": "gainwending",
    "contribute": "pitch in",
    "contributed": "pitched in",
    "contributing": "pitching in",
    "contribution": "input",
    "contributions": "inputs",
    "contrite": "sheepish",
    "contrition": "sorrow",
    "control": "lead",
    "conundrum": "riddle",
    "conurbation": "townclustering",
    "convect": "ibear",
    "convent": "nunring",
    "convention": "accoming",
    "convergence": "meeting",
    "conversation": "talk",
    "conversations": "talks",
    "converse": "speak",
    "conversely": "on the other hand",
    "convert": "wend",
    "convertible": "drophead",
    "convey": "give",
    "convict": "lag",
    "convince": "wheedle",
    "convoy": "wain row",
    "cooperate": "work together",
    "cooperative": "neatship",
    "cop": "hound",
    "cope": "deal",
    "copious": "beteeming",
    "copper": "ar",
    "coppern": "arn",
    "coppery": "ary",
    "copse": "thicket",
    "copy": "twin",
    "coral": "limeshaft",
    "cord": "fasten",
    "cordial": "friendly",
    "cords": "manstows",
    "corduroy": "ribbed cloth",
    "core": "kernel",
    "coriander": "cloveleaf",
    "cormorant": "sea raven",
    "cornea": "hornweb",
    "corneas": "hornwebs",
    "corner": "nook",
    "coronation": "kinehelming",
    "corporeal": "bodily",
    "corporation": "businessbody",
    "corpse": "body",
    "corpses": "bodies",
    "corpus": "body",
    "Corpus Christi": "Wistforwandering Day",
    "correct": "right",
    "correction": "righting",
    "correspond": "match",
    "corridor": "hallway",
    "corroborate": "bear out",
    "corrode": " gnaw",
    "corrugated": "wrizzled",
    "corrupt": "crooked",
    "corslet": "byrnie",
    "corvework": "workrede",
    "cosmetics": "fards",
    "cosmetic": "fard",
    "cosmolabe": "tungleheight meter",
    "cosmopolitan": "worldly",
    "cost": "outlay",
    "costs": "outlays",
    "costly": "dear",
    "costume": "outfit",
    "costumes": "outfits",
    "cottage": "hut",
    "cottager": "cotsettle",
    "cotton": "seedwool",
    "council": "gathering",
    "counsel": "lead",
    "counseling": "leading",
    "counselor": "alderman",
    "counselors": "aldermen",
    "count": "earl",
    "countenance": "cast",
    "counter ": "with",
    "counterbalance": "offset",
    "counterclockwise": "withershins",
    "counterculture": "otherway",
    "counterfeit goods": "apeware",
    "counterpart": "match",
    "countersign": "gaintoken",
    "counterstroke": "witherclap",
    "country": "land",
    "countries": "lands",
    "county": "shire",
    "coup": "strike",
    "d'etat": "state",
    "coupling traincarriage": "thill",
    "coupon": "deemslip",
    "courage": "mettle",
    "courageous": "bold",
    "course": "line",
    "course academic": "learnset",
    "court": "hof",
    "courteous": "fairspoken",
    "courtyard": "hallyard",
    "cousin": "kinswoman",
    "coven": "witchring",
    "covenant": "oath",
    "cover": "thatchthack",
    "coverage": "yondfetching",
    "covered area": "deck",
    "covering": "skin",
    "cover with": "lay on",
    "covert": "hidden",
    "coverup": "whitewash",
    "covet": "crave",
    "covetous": "greedy",
    "COVID": "GABAS (garlandbane ſickneſs)",
    "coward": "wimp",
    "cowardly": "gutless",
    "coworker": "byworker",
    "CPU": "main chip",
    "cranium": "skull",
    "crater": "bowl calque",
    "cravat": "necktie",
    "crayon": "waxlimestone",
    "cream": "salve",
    "crease": "wrinkle",
    " create": "beget",
    "creation": "brainchild",
    "creative": "shaperly",
    "creator": "maker",
    "creature": "wight",
    "credence": " belief",
    "credibility": "liefworthiness",
    "credible": "liefworthy",
    "credit": "hail",
    "creed": "belief",
    "cremate": "bale",
    "crepuscular": "twilighty",
    "crepuscule": "twilight",
    "crescent": "moonsickle",
    "crest": "ridge",
    "cretaceous": "chalken",
    "cretin": "blighter",
    "crevasse": "cleft",
    "crevice": "cleft",
    "crewel": "woolyarn",
    "crime": " lawbreaking",
    "criminal": "crook",
    "crimson": "deepred",
    "crisis": "needtime",
    "criterion": " yardstick",
    "critic": "scather",
    "critical": "weighty",
    "criticize": "slag",
    "criticism": " scathing",
    "crocodile": "nicker",
    "croissant": "moonbread",
    "cross ON": "thwarse",
    "crown": "kinehelm",
    "crucifix": "rood archaic",
    "crucify": "roodfasten",
    "crucifixion": "onrood",
    "crude": "rough",
    "cruel": "harsh",
    "cruelty": "meanness",
    "cruise": "thwarse",
    "cruiser": "thwarser",
    "crusade": "krosscampagne",
    "crusades": "krosscampagnes",
    "crust": "rind",
    "crustacean": "crab",
    "cry": "weep",
    "cryogenic": "coldly",
    "cryotherapy": "coldbehandling",
    "crypt": "thesterlock",
    "cryptocurrency": "keepminthood",
    "cryptography": "hiddenwriting",
    "crystal": "hursten",
    "crystalline": "hursty",
    "cub": "whelp",
    "cube": "worvel",
    "cuckoo": "yeke",
    "cucumber": "greenpod",
    "cuisine": "kitchen",
    "cull": "pickings",
    "culminate": "nib",
    "cultivate": "till",
    "culture": " couth",
    "culvert": "leat",
    "cuneiform bones": "wedgebones",
    "cuneiform writing": "wedgeshaped writing",
    "cure": "heal",
    "curiosity": "witfire",
    "curious": "funny",
    "curlew": "whaup",
    "currency": "minthoodt",
    "current": "run",
    "currently": "as of yet",
    "curriculum": "learnplot",
    "cursive": "handwritten",
    "cursor": "runner",
    "curtail": "cut back",
    "curtain": "hanger",
    "curve": "bow",
    "custody": " hold",
    "custard": "stich",
    "custom": "wone",
    "customary": " wonely",
    "customization": "besunderledge",
    "cutaneous": "skin",
    "cute": "pretty",
    "cutlass": "backsword",
    "cutlery": "silverware",
    "cycad": "firtapfolm",
    "cyclist": "wheeler",
    "cyclone": "whirlwind",
    "cygnet": "swanling",
    "cylinder": "rollshape",
    "cynical": "sneering",
    "cynosure": "hoardvat",
    "czar": "Russlander highking",
    "tsar": "Russlander highking",
    "tsars": "Russlander highkings",
    "czars": "Russlander highkings",
    
    
  "dairy": "milkhouse",
  "damage": "scathe",
  "damaged": "scathed",
  "damaging": "bad",
  "damn": "hex",
  "damned": "hexed",
  "damnation": "hexing",
  "damsel": "maid",
  "dance": "step",
  "dandelion": "horsebloom",
  "danger": "threat",
  "dangering": "threatening",
  "dangerous": "threatful",
  "dart": "darth dara",
  "data": "rawput",
  "database": "rawputholder",
  "date": "dealmark",
  "datefruit": "palmapple",
  "dative case": "forgivingly",
  "daub": "befoul",
  "de": "un",
  "deactivate": "switch off",
  "debate": "moot",
  "debatable": "mootfit",
  "debris": "trash",
  "debt": "shild",
  "debut": "beginning",
  "decade": "yearten",
  "decapitate": "behead",
  "decapitating": "beheading",
  "decapitated": "beheaded",
  "decay": "foul",
  "decayed": "fouled",
  "deceased": "breathless",
  "deceit": "misleading",
  "deceive": "swike",
  "December": "Ereyule",
  "decent": "good",
  "decentralization": "outkerneling",
  "deception": "cheating",
  "deceptive": "cheatful",
  "decide": "choose",
  "deciduous": "leafshedding",
  "decision": "call",
  "decisive": "allout",
  "declaration": "boding",
  "declare": "bode",
  "declared": "boded",
  "declaring": "boding",
  "declination": "dwining",
  "decline": "dwindle",
  "declined": "dwindled",
  "decoction": "mixling",
  "decorate": "bedeck",
  "decorating": "bedecking",
  "decoration": "bedecking",
  "decrease": "shrink",
  "decreased": "shrank",
  "decreasing": "shrinking",
  "decree": "behest",
  "decrepit": "timeworn",
  "dedicate": "earmark",
  "dedicated": "earmarked",
  "dedication": "earmarking",
  "defame": "file",
  "default": "flaw",
  "defeat": "beat",
  "defeated": "beat",
  "defeating": "beating",
  "defeaten": "beat",
  "defecate": "drite",
  "defecated": "drited",
  "defecating": "driting",
  "defecatation": "driting",
  "defect": "blight",
  "defected": "blighted",
  "defecting": "blighting",
  "defection": "blighting",
  "defend": "beshield",
  "defended": "beshielded",
  "defending": "beshielding",
  "defenestrate": "outwindow",
  "defense": "ward",
  "deficiency": "dearth",
  "deficient": "wanting",
  "deficit": "shortfall",
  "defile": "befile",
  "define": "mark off",
  "definitely": "markedly",
  "definition": "wordmark",
  "deflect": "offdrive",
  "deform": "misshape",
  "deformed": "misshapen",
  "deformity": "blight",
  "defragment": "cleave",
  "defraud": "swindle",
  "defrauding": "swindling",
  "defrauded": "swindled",
  "defrost": "thaw",
  "defrosted": "thawed",
  "defrosting": "thawing",
  "deforestation": "thawing",
  "defy": "flout",
  "defying": "flouting",
  "degenerate": "rotten",
  "degenerating": "rottening",
  "degeneration": "rotting",
  "degrade": "bemean",
  "degraded": "bemeaned",
  "degrading": "bemeaning",
  "degree": "step",
  "deify": "begod",
  "deifying": "begoding",
  "deity": "God",
  "Deism": "Godtroth",
  "delay": "stall",
  "dejected": "beaten down",
  "delete": "forwipe",
  "deleted": "forwiped",
  "deliberate": "think about",
  "delicious": "smakely",
  "delight": "queemness",
  "delightful": "queemful",
  "delimit": "mire",
  "delirious": "bewildered",
  "deliver": "bear",
  "delivered": "beared",
  "deliverer": "aleasand",
  "delivery": "childbirth",
  "delude": "mislead",
  "deluding": "misleading",
  "deluded": "misled",
  "deluge": "flood",
  "delusion": "misbelief",
  "delusional": "misbeliever",
  "demeanour": "jib",
  "dementia": "madness",
  "demilitarized": "unweaponed",
  "demilitarize": "unweapon",
  "demilitarise": "unweapon",
  "demilitarised": "unweaponed",
  "demise": "downfall",
  "demiurge": "craftsman",
  "democracy": "shiremight",
  "democractic": "shiremightly",
  "democracts": "shiremights",
  "democract": "shiremight",
  "demodulation": "backrighting",
  "demograph": "folk outline",
  "demolish": "tear down",
  "demolition": "wipeout",
  "demon": "fiend",
  "demonstrate": "show",
  "dendrite": "sinewtwig",
  "dendrochronology": "treering-timetelling",
  "dendrology": "treelore",
  "dengue": "breakbone",
  "denial": "naysay",
  "denyed": "naysaid",
  "denying": "naysaying",
  "denigrate": "slighten",
  "denomination": "benaming",
  "denote": "betoken",
  "denouement": "unravelling",
  "dense": "thick",
  "density": "crowd huddlethickness",
  "dentist": "toothleech cf Dn tandlge",
  "denude": "strip",
  "deny": "gainsay",
  "deodorant": "unsmeller",
  "deoxyribonucleic acid": "unasourseedsweetkernly sour",
  "depart": "leave",
  "departing": "farewell",
  "departure": "farewell",
  "department": "ambight",
  "depend": "hang",
  "dependence": "onhanginess",
  "dependent": "hingey",
  "depict": "show",
  "depreciate": "cheapen",
  "depressed": "beaten down",
  "depression": "blues",
  "deprivation": "lack",
  "deprive of": "bereave",
  "deputy": "outfader",
  "deracinate": "uproot",
  "deranged": "crazed",
  "deregulation": "unreding",
  "derivative": "upleading",
  "derive": "come from",
  "derived": "forthbrought",
  "dermatology": "hidelore",
  "dermis": "hide",
  "derogatory": "aworthly",
  "desacralize": "unhallow",
  "descend": "fall",
  "descendant": "offspring",
  "descendants": "offsprings",
  "descent": "downcoming",
  "descending": "downcoming",
  "describe": "bewrite",
  "description": "bewriting",
  "desecrate": "unhallow",
  "desk": "writboard",
  "desert": "dryland",
  "deserter": "heraflighter OE hereflma",
  "deserving": "meedful",
  "design": "layout",
  "designate": "betoken",
  "desinfectant": " ithersmite",
  "desire": "crave",
  "desirous": "wishful",
  "desist": "leave off",
  "desolate": "barren",
  "desolation": "aweestness",
  "despair": "hopelessness",
  "desperate": "hopeless",
  "despondency": "atsprungness OE tsprungnes",
  "despise": "hate",
  "despite": "although",
  "dessert": "afters",
  "destination": "goalspot",
  "destine": "tee",
  "destiny": "lot",
  "destroy": "fordo",
  "destruction": "breakdown",
  "detail": "meal OE ml",
  "detain": "hold",
  "detective": "sleuth",
  "deteriorate": "worsen",
  "determine": "name",
  "detest": "hate",
  "detracting": "backbiting",
  "detractor": "backbiter",
  "detrimental": "harmful",
  "devail": "fiend",
  "devil": "fiend",
  "devalue": "cheapen",
  "devastate": "ransack",
  "devastation": "Def 1 wreckage",
  "develope": "grow",
  "developed": "grown",
  "development": "growing",
  "developmental": "growth",
  "device": "tool",
  "devious": "shrewd",
  "devise": "think up",
  "devolve": "netherwind",
  "devote": "earmark",
  "devour": "fret",
  "devout": "downtheline",
  "dexterity": "deftness",
  "dexterous": "deft",
  "di ": "twi",
  "diabetes": "sweethurstsickness",
  "diabetic": "sweethurstsickened",
  "diabolic": " fiendish",
  "diacritic": "mark",
  "diresisdiresis": "break",
  "diagonal": "leaning",
  "dialect": "streettalk sometimes",
  "diameter": "bore",
  "diameter inner": "inner bore",
  "diamond": "hardore",
  "diaphanous": "sheer",
  "diaphragm": "midrith",
  "diarrhoea": "skitter",
  "diary": "daybook",
  "diaspora": "yondseeding",
  "dichotomy": "twidealing",
  "dictator": "king",
  "dictatorship": "Fulldightership",
  "dictionary": "wordbook",
  "die Theedish": "wirple",
  "diet": "foodline",
  "differ": "undershed",
  "difference": "otherness",
  "different": "other",
  "differentiation mathematics": "beshedding",
  "differently": "otherwise",
  "difficult": "pickandshovel",
  "difficulty": "hardship",
  "diffident": "withdrawn",
  "digit": "finger",
  "digital": "scorely",
  "dignity": "worth",
  "digraph": "twiwrit",
  "digress": "umsweep",
  "dilapidated": "threadbare",
  "dilate": "abreethe",
  "diligent": "tiedup",
  "diminish": "lessen",
  "dimension": "breadth",
  "dilletante": "short thinke",
  "diminutive": "tiny",
  "dimorphism": "twoshapenness",
  "diningroom": "buttern",
  "dinner": "evening meal",
  "dinosaur": "dreadask",
  "diocese": "bedereve shire",
  "diphthong": "twithedin",
  "diploma": "douth writ",
  "direct": "lead",
  "direction": "heading",
  "directory": "threadlist",
  "dis": "mis",
  "disability": "behindering",
  "disable": "cripple",
  "disabled": "lame",
  "disadvantage": "afterdeal",
  "disadvantaged": "hindered",
  "disappear": "flee",
  "disappoint": "let down",
  "disarm": "andweapon",
  "disarrange": "rumple",
  "disaster": "shipwreck",
  "disastrous": "baneful",
  "discalced": "barefoot",
  "discard": "get rid of",
  "discharge": "unload",
  "disciple": "loreknight",
  "discipline": "school",
  "disclaim": "foreswear",
  "disclaimer": "forsaker",
  "disclose": "bare",
  "disconcert": "taken aback",
  "disconcerting": "offputting",
  "discontinue": "cut",
  "discount": "falloff",
  "discourse": "talk",
  "discover": "find out",
  "discovery": "finding",
  "discredit": "smirch",
  "discredited": "smirched",
  "discriminate": "beshed",
  "discrimination": "beshedding",
  "discriminated": "besheded",
  "discuss": "wordwrestle",
  "disease": "addle",
  "disfigure":  "mar",
  "disgrace": "shend",
  "disgraceful": "shameful",
  "disgusting": "loathely",
  "dishevelled": "cluttered",
  "dishonourable": "arless",
  "disinclined": "loath",
  "disinfect": "unsmittle",
  "disinfectant": "unsmittler",
  "disk": "flat",
  "dislike": "mislike",
  "dislocate": "unstead",
  "dismember": "alithe",
  "dismiss": "snub",
  "disobedience": "overhearness",
  "disobedient": "unhold",
  "disordered": "unsided",
  "dispatch": "send off",
  "disperse": "scatter",
  "displace": "uproot",
  "display": "fair",
  "displease": "misqueme",
  "disposable": "throwaway",
  "disposal": "deepsix",
  "disposition": "heart",
  "disprove": "belie",
  "dispute": "bicker",
  "disqualify": "unfit",
  "disregard": "overlook",
  "disrupt": "upset",
  "dissect": "sithe",
  "dissemble": "bluff",
  "dissolution": "breakup",
  "dissonance": "infighting",
  "distance": "lead",
  "distant": "away",
  "distill": "drop",
  "distinct": "marked",
  "distinguish": "makeout",
  "distort": "misshape",
  "distract": "throw off",
  "distraught": "worked up",
  "distress": "bother",
  "distress signal": "woecall",
  "distribute": "deal out",
  "distribution": "dealing",
  "district": "neighbourhood",
  "distrust": "forthink",
  "disturb": "stir",
  "disturbance": "stir",
  "disturbing": "creepy",
  "diurnal": "daily",
  "diverse": "manikind",
  "diversify": "manikind",
  "divert": "offlead",
  "divide": "cleave",
  "divination": "foretelling",
  "divine": "Godly",
  "divinity": "holiness",
  "division": "cleaving",
  "divorce": "wedbreach",
  "DNA": "twisted ladder",
  "dna": "twisted ladder",
  "docile": " meek",
  "doctor": "healer",
  "doctrine": "lorespell",
  "document": "leafwrit",
  "documentary": "broadcast",
  "dogma": "setinstone thinking",
  "dogmatic": "setinstone",
  "dolphin": "mereswine",
  "domain": "lorddom",
  "dome": "cupple",
  "domestic": "homeland",
  "domesticate": "tame",
  "domicile": "grith",
  "dominate": "lord over",
  "donate": "bestow",
  "donation": "gift",
  "doppelgänger": "lookalike",
  "dormant": "sleeping",
  "dormitory": "bedroom",
  "dorsal": "back",
  "dosage": "muchness",
  "double": "twin",
  "doubt": "qualm",
  "doubtful": "twiminded",
  "douse": "drench",
  "dozen": "tens",
  "dozens": "tens",
  "draconian": "harsh",
  "dragon": "lindworm",
  "dragonfly": "adderbolt",
  "drainage basin": "watershed",
  "drama": "play",
  "dramatic": "hammy",
  "dramatist": "playwright",
  "dress": "clothe",
  "dromadary": "drylander",
  "drupe": "stoneberry",
  "dual": "twin",
  "dub": "name",
  "dubious": "dodgy",
  "duchy": "earldom",
  "due": "owing",
  "duel": "ballgame",
  "duet": "twising",
  "dugong": "seacow",
  "duke": "earl",
  "dunce": "mouthbreather",
  "dune": "sandhill",
  "duplication": "twofoldness",
  "during": "throughout",
  "Dutchman": "Lowlander",
  "duvet": "bedspread",
  "dynamic": "snell",
  "dynasty": "erverike",
  "dysentery": "reddri",
  "dysfunctional": "unworking",
  "dyslexic": "wordblindness",
  "dystopia": "torestead"


}
