/* 

The words in the wordbook must start with a lowercase letter, and cannot contain spaces
since the translator uses the space character to make up the words, meaning that a space
would be recognised as a marker for the end of a word and start of a new one, rather than a part of the word
like in the case of a cappella, which is why the word is written as acappella in the wordbook.

*/


var wordbook = {
    'acappella': 'mouthglee',
    'acappellas': 'mouthglees',
    'a-la-carte': 'by-the-list',
    'aardvark': 'antbear',
    'aardvarks': 'antbears',
    'abacus': 'reckonboard',
    'abacuses': 'reckonboards',
    'abandon': 'forsake',
    'posteriorly': 'abaft',
    'abandonment': 'forsaking',
    'abandoned': 'forsook',
    'abase': 'shame',
    'abased': 'shamed',
    'abasing': 'shaming',
    'abash': 'ashame',
    'abashed': 'ashamed',
    'abate': 'ease',
    'abated': 'eased',
    'abating': 'easing',
    'abattoir': 'slaughterhouse',
    'abattoirs': 'slaughterhouses',
    'abbess': 'mother',
    'abbreviation': 'offshortening',
    'abbreviations': 'offshortenings',
    'abbreviate': 'offshorten',
    'abdicate': 'step down',
    'abdicated': 'stepped down',
    'abdication': 'stepping down',
    'abdomen': 'quith',
    'abdomens': 'quithes',
    'abduct': 'kidnap',
    'abduction': 'kidnapping',
    'abducted': 'kidnapped',
    'aberrant': 'black-sheep',
    'aberration': 'way-outness',
    'abet': 'goad',
    'abetted': 'goaded',
    'abetting': 'goading',
    'abhor': 'loathe',
    'abhorred': 'loathed',
    'abhorring': 'loathing',
    'ability': 'skill',
    'abilities': 'skills',
    'abject': 'low',
    'abjure': 'forswear',
    'abjured': 'forsworn',
    'abjuring': 'forswearing',
    'ablactate': 'wean',
    'ablactated': 'weaned',
    'ablation': 'offtaking',
    'ablations': 'offtakings',
    'ablative': 'atbraidingly',
    'ablaut': 'offlloud',
    'able': 'fit',
    'ablute': 'wash',
    'ablution': 'washing',
    'abluted': 'washed',
    'abnegate': 'forgo',
    'abnegated': 'forwent',
    'abnegation': 'forgoing',
    'abnormal': 'amiss',
    'abnormality': 'amissitty',
    'abolish': 'end',
    'abolished': 'ended',
    'abolition': 'ending',
    'abominable': 'loathsome',
    'aboriginal': 'inborn',
    'aboriginals': 'firstfolks',
    'aborigine': 'firstfolk',
    'abort': 'lay off',
    'aborted': 'laid off',
    'abortion': 'forbirthing',
    'abound': 'overflow',
    'abounded': 'overflowed',
    'abounding': 'overflowing',
    'abrasion': 'graze',
    'abridge': 'forshorten',
    'abridged': 'foreshortened',
    'abridging': 'foreshortening',
    'abrupt': 'anon',
    'abruptly': 'anonly',
    'abscond': 'break out',
    'absconded': 'broke out',
    'absconding': 'breaking out',
    'absence': 'offwardness',
    'absent': 'offward',
    'absenteeism': 'offwardness',
    'absent-mindedness': 'daydreaming',
    'absinthe': 'wormwood drink',
    'absolute': 'outright',
    'absolution': 'outrightly',
    'absolutely': 'wholly',
    'absolve': 'forgive',
    'absolved': 'forgave',
    'absolving': 'forgiving',
    'absorb': 'up-soak',
    'absorbed': 'up-soaked',
    'absorbing': 'up-soaking',
    'absorbtion': 'up-soaking',
    'abstain': 'withhold',
    'abstaining': 'withholding',
    'abstained': 'withheld',
    'abstinence': 'forhaveness',
    'abstract': 'dreamlike',
    'abstraction': 'dreamlikeness',
    'abundance': 'fullsomeness',
    'abundant': 'overflowing',
    'abuse': 'scathe',
    'abused': 'scathed',
    'abusing': 'scathing',
    'abysmal': 'lowest',
    'abyss': 'netherworld',
    'acacia': 'thorntree',
    'academia': 'loredom',
    'academic': 'lorewise',
    'açaí': 'koleberry',
    'accede': 'thware',
    'accede': 'thwared',
    'acceding': 'thwareing',
    'accelerate': 'swiften',
    'accelerating': 'swifting',
    'acceleration': 'swifteness',
    'accent': 'tonguefall',
    'accept': 'ontake',
    'accepted': 'ontook',
    'acceptable': 'thewsome',
    'access': 'gateway',
    'accessed': 'gatewayed',
    'accessible': 'at hand',
    'accessory': 'deedmate',
    'accident': 'befall',
    'accidental': 'unwitting',
    'accompany': 'follow',
    'accompanied': 'followed',
    'accomplish': 'fulfill',
    'accomplishing': 'fulfilling',
    'accord': 'deal',
}
